alert('hello,xiarui');
alert(1+1);
alert(Math.sqrt(1+1));
alert(sqrt2+sqrt3);
alert(1/0);
alert(0/0);
alert(2+3);
alert(Math.sqrt('2'+'3'));
alert(Math.sqrt('2')+Number('3'))
alert('2'+3);
alert(number('2')+3)
